app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from . import views

urlpatterns = i18n_patterns(
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('candles/', include('candles.urls', namespace='candles')),
)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n"))
]

app/candles/urls.py
""" Urls for tabs 'Settings of securities', 'Candles', 'Returns'."""
import django.urls as dj_urls
from . import views


app_name = 'candles'

urlpatterns = [
    dj_urls.path('', views.getCandlesPreview, name='list'),
    dj_urls.path('candlesData/', views.getCandles, name='candlesData'),
    dj_urls.path('returnsTask/', views.returnsTask, name='returnsTask'),
    dj_urls.path('trackingSettings/', views.SecuritySettingListView.as_view(), name='settingList'),
    dj_urls.path('trackingSettings/add/',
                 views.createSecuritySetting, name='settingCreate'),
    dj_urls.path('trackingSettings/addTopByCapStocks/',
                 views.addStocksTopByCap, name='addTopByCapStocks'),
    dj_urls.path('trackingSettings/chooseAction/', views.chooseAction, name='chooseAction'),
    dj_urls.path('trackingSettings/bulkDeleteConfirm/',
                 views.bulkDeleteConfirm, name='settingBulkDeleteConfirm'),
    dj_urls.path('trackingSettings/<pk>/edit/', views.updateSecuritySetting, name='settingUpdate'),
]

app/candles/forms.py
""" Forms for tabs 'Settings of securities', 'Candles', 'Returns'."""
import datetime
from django import forms
from django.core.exceptions import ValidationError
import django.db.models as dj_models
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext as __
from account.forms import HeplerMixin
from . import models, const


class SecurityForm(HeplerMixin, forms.ModelForm):

    class Meta:
        model = models.Security
        fields = ['engine', 'market', 'security']


class FetchSettingForm(HeplerMixin, forms.ModelForm):

    class Meta:
        model = models.FetchSetting
        fields = ['duration', 'interval']


class UserSecuritySettingsForm(HeplerMixin, forms.ModelForm):

    class Meta:
        model = models.UserSecurityFetchSetting
        fields = ['max_update_rate']


def validateMinDuration(value: datetime.timedelta) -> None:
    if value < ReturnsTaskForm.DURATION_MIN_VAL:
        raise ValidationError(_('Min value of duration is 1 hour.'))


class ReturnsTaskForm(HeplerMixin, forms.Form):
    DURATION_MIN_VAL = datetime.timedelta(hours=1)  # minimal value of duration field

    class Rule(dj_models.TextChoices):
        OC = const.RULE_OC, _('Open-Close')
        HL = const.RULE_HL, _('High-Low')

    class OrderingField(dj_models.IntegerChoices):
        # Index of column to order deals table.
        F0 = 0, _('Return per year without reinvesting')
        F1 = 1, _('Return per year with reinvesting')
        F2 = 2, _('Return per deal')
        F9 = 9, _('Sharpe ratio')
        F10 = 10, _('Sortino ratio')
        F11 = 11, _('Max drawdown')
        F12 = 12, _('Calmar ratio')
        # F13 = 13, _('Standard deviation') # asc?
        F14 = 14, _('Alpha')
        # F15 = 15, _('Beta') # abs() asc?
        F16 = 16, _('Treynor ratio')
        # F17 = 17, _('R squared 1')
        # F18 = 18, _('R squared 2')
        F19 = 19, _('Information ratio')

    duration = forms.DurationField(
        required=True, initial=datetime.timedelta(days=1), label=_('Duration'),
        help_text=_('Format: DD HH:MM:SS.uuuuuu. All calculations will be based '
                    'only on (Current time - Duration) time period. Min value is 1 hour.'),
        validators=[validateMinDuration])
    feeIn = forms.FloatField(min_value=0.0, initial=0.0, required=True, label=_('Fee to buy'),
                             help_text=_('In percentages.'))
    feeOut = forms.FloatField(min_value=0.0, initial=0.0, required=True, label=_('Fee to sell'),
                              help_text=_('In percentages.'))
    loanFee = forms.FloatField(min_value=0.0, initial=0.0, required=True, label=_('Loan fee'),
                               help_text=_('In percentages (percentage per annum).'))
    riskFreeReturn = forms.FloatField(
        min_value=0.0, initial=0.0, required=True, label=_('Risk free return'),
        help_text=_('In percentages (percentage per annum).'))
    isPerYear = forms.BooleanField(
        initial=True, required=False, label=_('Per year'),
        help_text=_('Should deals be selected by return per year (true) or by return per trade (false)?'))
    rule = forms.ChoiceField(
        choices=Rule.choices, initial=Rule.OC, required=True, label=_('Rule'),
        help_text=_('What OHLC values should be used for return calculation?'))
    numRows = forms.IntegerField(
        min_value=1, initial=10, max_value=1000, required=True, label=_('Number of rows'),
        help_text=_('Number of rows in every result table.'))
    orderingField = forms.ChoiceField(
        choices=OrderingField.choices, initial=OrderingField.F2, required=True,
        label=_('Ordering field'),
        help_text=_('What field should be used to order best 1 deal returns?'))

    def cleanedDataAsStr(self) -> str:
        """ Represent form cleaned data as string."""
        cd = self.cleaned_data
        cd['duration'] = datetime.timedelta(seconds=cd['duration'])
        res = ', '.join([f"{fieldObj.label}: {cd[name]}" for name, fieldObj in self.fields.items()])
        return res

app/candles/views.py
""" Views for tabs 'Settings of securities', 'Candles', 'Returns'."""
import datetime
import logging
from typing import Any
import celery.result
import celery.states
from django.core.paginator import Paginator
import django.db.models as dj_models
import django.db.utils as dj_db_utils
from django.http import HttpResponseRedirect, JsonResponse
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView
from django.contrib import messages as dj_messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from app.redis_app import redisApp
from . import models, forms, download, tasks

POST = 'POST'
MENU_SECTION_SETTINGS = 'SecuritySettings'

logger = logging.getLogger('custom_debug')


def removeUnusedFetchedData(fetchedDataPks: list) -> None:
    """ Remove all models.FetchedData objects with id from fetchedDataPks
        that aren't used in usersecurityfetchsetting db table.
    Args:
        fetchedDataPks (list): primary keys of models.FetchedData objects
    """
    fetchedDataPks = [pk for pk in fetchedDataPks if pk]
    if not fetchedDataPks:
        return
    res = models.FetchedData.objects.filter(
        pk__in=fetchedDataPks, usersecurityfetchsetting__isnull=True).only('pk').delete()
    logger.debug(f'Removed FetchedData objs: {res}')


class Messages:
    """ Hints to user."""
    EDIT_SUCCESS = _('The changes were saved successfully')
    EDIT_ERROR = _('Errors occurred during the update')
    ADD_SUCCESS = _('The operation was successful')
    ADD_ERROR = _('Errors occurred during the operation')
    DELETE_SUCCESS = ADD_SUCCESS
    CREATE_TASK_SUCCESS = _('The task was successfully created')
    SETTING_EXIST = _('Settings with the same parameters #1 - #5 already exist.')


class SecuritySettingListView(LoginRequiredMixin, ListView):
    """ View for displaying ... """
    template_name = 'securitySettings/list.html'
    context_object_name = 'securitySettings'
    model = models.UserSecurityFetchSetting
    ordering = ('sequence_number',)

    MENU_SECTION = MENU_SECTION_SETTINGS

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        """ Add object_list to the context, generate response.
        Args:
            request (HttpRequest): user request
        Returns:
            HttpResponse: response for user
        """
        self.__request = request
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> dj_models.query.QuerySet:
        queryset = self.__class__.model.objects.filter(user_id=self.__request.user)\
            .prefetch_related(models.FetchedData.getPrefetchObjWoDataFields())
        ordering = self.get_ordering()
        if ordering:
            queryset = queryset.order_by(*ordering)
        return queryset

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """ Collect additional data for displaying the list of objects.
        Returns:
            dict[str, Any]: context data
        """
        context = super().get_context_data(**kwargs)
        context['section'] = self.__class__.MENU_SECTION
        return context


@login_required
def createSecuritySetting(request: HttpRequest) -> HttpResponse:
    """ View for creation of models.UserSecurityFetchSetting objects using
        several different forms as one large form.
    """
    template_name = 'securitySettings/create.html'
    success_url = reverse_lazy('candles:settingList')
    MENU_SECTION = MENU_SECTION_SETTINGS

    if request.method == POST:
        security_form = forms.SecurityForm(request.POST)
        fetchSetting_form = forms.FetchSettingForm(request.POST)
        userSecuritySettings_form = forms.UserSecuritySettingsForm(request.POST)

        if security_form.is_valid() and fetchSetting_form.is_valid() and \
                userSecuritySettings_form.is_valid():
            security, __ = models.Security.objects.get_or_create(
                **security_form.cleaned_data)
            fetch_setting, __ = models.FetchSetting.objects.get_or_create(
                **fetchSetting_form.cleaned_data)
            fetched_data, __ = models.FetchedData.objects\
                .only('security', 'fetch_setting').get_or_create(
                    security=security, fetch_setting=fetch_setting)

            maxSeqNum = models.UserSecurityFetchSetting.objects.filter(user=request.user)\
                .aggregate(maxSeqNum=dj_models.Max('sequence_number')).get('maxSeqNum') or 0

            userSecuritySettings_form.instance.user = request.user
            userSecuritySettings_form.instance.fetched_data = fetched_data
            userSecuritySettings_form.instance.sequence_number = maxSeqNum + 1
            userSecuritySettings_form.instance.has_error = None

            try:
                userSecuritySettings_form.save()
            except dj_db_utils.IntegrityError:
                dj_messages.error(request, Messages.SETTING_EXIST)
            else:
                dj_messages.success(request, Messages.ADD_SUCCESS)
                return HttpResponseRedirect(success_url)
        else:
            dj_messages.error(request, Messages.ADD_ERROR)
    else:
        security_form = forms.SecurityForm()
        fetchSetting_form = forms.FetchSettingForm()
        userSecuritySettings_form = forms.UserSecuritySettingsForm()

    return render(request, template_name,
                  {'security_form': security_form, 'fetchSetting_form': fetchSetting_form,
                   'userSecuritySettings_form': userSecuritySettings_form,
                   'section': MENU_SECTION})


@login_required
def updateSecuritySetting(request: HttpRequest, pk: int) -> HttpResponse:
    """ View for updating models.UserSecurityFetchSetting objects using
        several different forms as one large form."""
    template_name = 'securitySettings/update.html'
    success_url = reverse_lazy('candles:settingList')
    model = models.UserSecurityFetchSetting
    MENU_SECTION = MENU_SECTION_SETTINGS

    obj = get_object_or_404(model, pk=pk, user=request.user)
    security = obj.fetched_data.security
    fetch_setting = obj.fetched_data.fetch_setting

    if request.method == POST:
        security_form = forms.SecurityForm(instance=security, data=request.POST)
        fetchSetting_form = forms.FetchSettingForm(instance=fetch_setting, data=request.POST)
        userSecuritySettings_form = forms.UserSecuritySettingsForm(instance=obj, data=request.POST)

        prevFetchedDataPk = None
        if security_form.is_valid() and fetchSetting_form.is_valid() and \
                userSecuritySettings_form.is_valid():
            if security_form.has_changed() or fetchSetting_form.has_changed():
                if security_form.has_changed():
                    security, __ = models.Security.objects.get_or_create(
                        **security_form.cleaned_data)
                if fetchSetting_form.has_changed():
                    fetch_setting, __ = models.FetchSetting.objects.get_or_create(
                        **fetchSetting_form.cleaned_data)

                fetched_data, __ = models.FetchedData.objects.only('security', 'fetch_setting')\
                    .get_or_create(security=security, fetch_setting=fetch_setting)

                prevFetchedDataPk = obj.fetched_data.pk
                userSecuritySettings_form.instance.fetched_data = fetched_data
                userSecuritySettings_form.instance.has_error = None
            try:
                userSecuritySettings_form.save()
            except dj_db_utils.IntegrityError:
                dj_messages.error(request, Messages.SETTING_EXIST)
            else:
                removeUnusedFetchedData([prevFetchedDataPk])
                dj_messages.success(request, Messages.EDIT_SUCCESS)
                return HttpResponseRedirect(success_url)
        else:
            dj_messages.error(request, Messages.EDIT_ERROR)
    else:
        security_form = forms.SecurityForm(instance=security)
        fetchSetting_form = forms.FetchSettingForm(instance=fetch_setting)
        userSecuritySettings_form = forms.UserSecuritySettingsForm(instance=obj)

    return render(request, template_name,
                  {'security_form': security_form, 'fetchSetting_form': fetchSetting_form,
                   'userSecuritySettings_form': userSecuritySettings_form,
                   'section': MENU_SECTION})


@login_required
def chooseAction(request: HttpRequest) -> HttpResponse:
    """ Call another view function depending on pressed button."""
    if request.method == POST:
        if request.POST.get('delete', None):
            return bulkDelete(request)
        if request.POST.get('setOrdering', None):
            return setOrdering(request)
    return HttpResponseBadRequest()


@login_required
def bulkDelete(request: HttpRequest) -> HttpResponse:
    """ View for removal of several or all model objects."""
    model = models.UserSecurityFetchSetting
    templateName = 'securitySettings/bulk_delete_confirm.html'
    itemName = 'list-group-item'
    MENU_SECTION = MENU_SECTION_SETTINGS

    if request.method == POST:
        itemIds = request.POST.getlist(itemName)
        nextAfterConfirmatn = request.POST.get('next_next', '/')
        deleteOption = request.POST.get('delete')

        if deleteOption == 'selected':
            items = model.objects.filter(id__in=itemIds, user=request.user)
        elif deleteOption == 'all':
            items = model.objects.filter(user=request.user)
        else:
            return HttpResponseBadRequest()

app/templates/candles/charts.html
{% if objects %}
    <div class="d-flex justify-content-between px-1">
        <label for="chartWidthRange" class="form-label px-1">Width</label>
        <input type="range" class="form-range" min="200" max="1500" value="730" id="chartWidthRange">
        <label for="chartHeightRange" class="form-label px-1 ms-3">Height</label>
        <input type="range" class="form-range" min="200" max="1500" value="680" id="chartHeightRange">
    </div>
{% endif %}
<div class="row justify-content-center mt-1" id="charts">
    {% if objects %}
        {% for obj in objects %}
            <div id="chart-{{ forloop.counter }}" class="mb-3" style="width:730px;height:680px;"></div>
        {% endfor %}
    {% endif %}
    {% include "pagination.html" with object_list=objects %}
</div>

app/templates/candles/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Securities tracking settings" %}{% endblock %}

{% block content %}
<div class="container-fluid p-1">
    <!-- Show spinner on load -->
    <div class="d-flex justify-content-center" id="spinner">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>    
    <div id="charts-container"></div>
</div>
{% endblock %}

{% block include_js %}
<script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>
<script type="text/javascript" src="{% static "js/showCharts.js" %}"></script>
<script type="text/javascript">
    let params = window.location.search;
    loadCharts("{% url "candles:candlesData" %}" + params);
</script>
{% endblock %}

app/templates/candles/result_table.html
{% load i18n %}
{% load my_tags %}

<table id="{{ tableLabel }}" class="table table-striped table-bordered border border-3 align-middle text-center caption-top">
    <thead class="sticky-top">
        <tr>
            <th scope="col" hidden>Chart id</th>
            <th scope="col">Return per year without reinvesting, %</th>
            <th scope="col">Return per year with reinvesting, %</th>
            <div class="container"><th scope="col">Return per deal, %</th></div>
            <th scope="col">Security</th>
            <th scope="col">Buy time</th>
            <th scope="col">Buy price</th>
            <th scope="col">Sell time</th>
            <th scope="col">Sell price</th>
            <th scope="col">Data time period</th>
            <th scope="col">Sharpe ratio</th>
            <th scope="col">Sortino ratio</th>
            <th scope="col">Max drawdown</th>
            <th scope="col">Calmar ratio</th>
            <th scope="col">Standard deviation</th>
            <th scope="col">Alpha</th>
            <th scope="col">Beta</th>
            <th scope="col">Treynor ratio</th>
            <th scope="col">R squared 1</th>
            <th scope="col">R squared 2</th>
            <th scope="col">Information ratio</th>
        </tr>
        <tr><th colspan="21" class="text-body-secondary border">
            Best {{ tableLabel }} found - <a href="{% url "candles:list" %}" id="allChartsUrl">all charts</a>
        </th></tr>
    </thead>
    <tbody>                    
        {% for row in returns %}
            <tr>
                {% for val in row %}
                    {% if forloop.counter == 1 %}                                    
                        {% with i=forloop.parentloop.counter|add:"-1" %}
                            <td hidden>{{ chartIds|index:i }}</td>
                        {% endwith %}                                    
                    {% endif %}
                    {% if forloop.counter == 4 %}
                        <td>
                            {% with i=forloop.parentloop.counter|add:"-1" %}
                                <a href="{% url "candles:list" %}?ids={{ chartIds|index:i }}">{{val}}</a>
                            {% endwith %}
                        </td>
                    {% else %}
                        <td>{{val}}</td>
                    {% endif %}
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>

app/templates/candles/return_task_create.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Create returns task" %}{% endblock %}

{% block content %}
<div class="row mt-4 mb-2">
  <div class="col-2"></div>
  <div class="col-8">
    <h3>{% trans "Create a task to calculate best returns" %}</h3>
    <form method="post">
      {% crispy task_form %}
      <input type="submit" value="{% trans "Create task" %}" class="btn btn-primary px-5 mt-2">
    </form>
  </div>
</div>
{% endblock %}

app/templates/candles/return_task_results.html
{% extends "base.html" %}
{% load i18n %}
{% load my_tags %}
{% block title %}{% trans "Returns task results" %}{% endblock %}
{% block content %}
<div class="container mt-2 mx-2">
    <p class=''>{% trans "Parameters of your request were" %}<br>{{taskParams}}</p>
    {% if failed %}
        <p class=''>{% trans "Your task has failed. Please click tab 'Returns' and create new task with other parameters." %}</p>
    {% elif inProgress %}
        <p class=''>{% trans "Your task is still in progress. Please click tab 'Returns' a bit later." %}</p>
    {% else %}
        {% if longReturns or shortReturns %}
            <h5>{% trans "Best returns based on data downloaded to show candle charts for different users" %}</h5>
        {% else  %}
            <p class=''>{% blocktrans %}
                There is no available fetched data for the entire range of parameter 'Duration'. 
                Please create objects on tab 'Settigns of securities', click tab 'Candles' 
                to fetch new data and then click tab 'Returns' to recreate your task.
                {% endblocktrans %}</p>
        {% endif %}
        {% if longReturns %}
            {% include "candles/result_table.html" with returns=longReturns tableLabel='longs' chartIds=longIds%}
        {% endif %}
        {% if shortReturns %}
            <br>
            {% include "candles/result_table.html" with returns=shortReturns tableLabel='shorts' chartIds=shortIds%}
        {% endif %}
    {% endif %}
</div>
{% endblock %}

{% block include_js %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    const COL_CHART_ID = 0;
    const COL_RETURN_PER_DEAL = 3;
    const COL_SECURITY = 4;

    function setAllChartsLink(table, tableSelector) {
        let allLinks = table.columns(COL_CHART_ID).data().eq(0).toArray();
        selector = tableSelector + ' > thead > tr > th > #allChartsUrl';
        let link = document.querySelector(selector).href;
        link = link.split('?ids=')[0] + '?ids=' + allLinks.join();
        document.querySelector(selector).href = link;
    }

    function changePageChartLinks(selector, column) {
        let rows = document.querySelector(selector).getElementsByTagName('tr');
        for (let i = 0; i < rows.length; i++) {
            let link = rows[i].getElementsByTagName('td')[column].querySelector('a').href;
            link = link.split('?ids=')[0] + '?ids=' + rows[i].getElementsByTagName('td')[0].innerText;
        }
    }

    function toDataTable(tableSelector, orderingInd) {
        const lengthMenu = [
            [10, 5, 3, 20, 50, -1],
            [10, 5, 3, 20, 50, 'All']
        ];
        const dom = '<"d-flex justify-content-between my-2"lf>tip'

        if (!document.querySelector(tableSelector)) {
            return;
        }

        let table = new DataTable(tableSelector, {
            lengthMenu: lengthMenu,
            dom: dom,
            order: [[+orderingInd + 1, 'desc']]
        });

        setAllChartsLink(table, tableSelector);

        table.on('order.dt', function (e, settings, ordArr) {
            changePageChartLinks(tableSelector + ' > tbody', COL_SECURITY);
            setAllChartsLink(table, tableSelector);
        });
    }

    toDataTable('#longs', '{{ orderingInd }}');
    toDataTable('#shorts', '{{ orderingInd }}');
</script>
{% endblock %}