app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from . import views

urlpatterns = i18n_patterns(
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('candles/', include('candles.urls', namespace='candles')),
)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n"))
]

app/candles/urls.py
""" Urls for tabs 'Settings of securities', 'Candles', 'Returns'."""
import django.urls as dj_urls
from . import views


app_name = 'candles'

urlpatterns = [
    dj_urls.path('', views.getCandlesPreview, name='list'),
    dj_urls.path('candlesData/', views.getCandles, name='candlesData'),
    dj_urls.path('returnsTask/', views.returnsTask, name='returnsTask'),
    dj_urls.path('trackingSettings/', views.SecuritySettingListView.as_view(), name='settingList'),
    dj_urls.path('trackingSettings/add/',
                 views.createSecuritySetting, name='settingCreate'),
    dj_urls.path('trackingSettings/addTopByCapStocks/',
                 views.addStocksTopByCap, name='addTopByCapStocks'),
    dj_urls.path('trackingSettings/chooseAction/', views.chooseAction, name='chooseAction'),
    dj_urls.path('trackingSettings/bulkDeleteConfirm/',
                 views.bulkDeleteConfirm, name='settingBulkDeleteConfirm'),
    dj_urls.path('trackingSettings/<pk>/edit/', views.updateSecuritySetting, name='settingUpdate'),
]

app/templates/securitySettings/bulk_delete_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Confirm delete" %}{% endblock %}

{% block content %}
<div class="container-sm m-5">
  <h3>{% trans "Confirm bulk delete" %}</h3> 
  <form method="post" action="{% url "candles:settingBulkDeleteConfirm" %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <ol class="list-group list-group-numbered">
        {% for item in items %}
        <input type="hidden" name="list-group-item" value="{{ item.id }}">
        <li class="list-group-item d-flex flex-wrap">
            <p class="mx-2">{{ item.fetched_data.security }}. {{ item.fetched_data.fetch_setting }}.</p>
        </li>
        {% endfor %}
    </ol>
    <div class="d-flex justify-content-around">
        <button type="submit" class="btn btn-primary px-5 mt-3">{% trans "Confirm delete" %}</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/securitySettings/create.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Add security" %}{% endblock %}

{% block content %}
<div class="row my-4">
  <div class="col-2"></div>
  <div class="col-8">
    <h3>{% trans "Add tracking of security" %}</h3>
    <form method="post" enctype="multipart/form-data">
      {% crispy security_form %}
      {% crispy fetchSetting_form %}
      {% crispy userSecuritySettings_form %}
      <button type="submit" class="btn btn-primary px-5 mt-2">{% trans "Add security tracking" %}</button>
    </form>
  </div>
</div>
{% endblock %}

app/templates/securitySettings/list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Securities tracking settings" %}{% endblock %}

{% block content %}
<div class="container-fluid p-2">
    <div class="row justify-content-between mt-1">      
        <div class="col-2"></div>
        <div class="col-8">
            {% if securitySettings %}
                <div class="row me-1 mt-1">
                    <div class="col-6 d-flex border border-2 rounded-2 border-light-subtle px-0">
                        <div class="col-2 d-flex align-self-center justify-content-center px-1 py-1">
                            <input type="checkbox" class="form-check-input" id="checkAll">          
                        </div>
                        <div class="col-10 d-flex align-self-center px-1 py-1">
                            <small class="text-body-secondary">{% trans "Select all objects on this page" %}</small>
                        </div>
                    </div>
                </div>

                <form method="post" action="{% url "candles:chooseAction" %}">
                    {% csrf_token %}
                    <input type="hidden" name="next_next" value="{% url "candles:settingList" %}">
                        <div id="sortable" class="ml-0 pl-0">              
                            {% for securitySetting in securitySettings %}
                                <div class="row border border-2 rounded-4 me-1 ml-0 pl-0 {% if securitySetting.has_error %}border-danger-subtle{% elif securitySetting.has_error is not None %}border-success-subtle{% else %}border-info-subtle{% endif %}">              
                                    <div class="col-1 d-flex align-self-center justify-content-center deleteObject px-1 py-1">
                                        <input type="checkbox" class="form-check-input" name="list-group-item" value="{{ securitySetting.id }}">
                                    </div>
                                    <div class="col-11 d-flex px-1 py-1">
                                        <a href="{{ securitySetting.get_absolute_url }}" class="list-group-item list-group-item-action" aria-current="true">
                                            {{ securitySetting.fetched_data.security }}<br>
                                            {{ securitySetting.fetched_data.fetch_setting }}<br>
                                            {% trans "Maximum candle refresh rate" %}: {{ securitySetting.max_update_rate }}
                                        </a>
                                    </div>                       
                                    <input type="hidden" name="list-ordering-item" value="{{securitySetting.sequence_number}}">         
                                </div>
                            {% endfor %}
                        </div>                   
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-outline-primary px-2 mt-2" name="delete" value="selected">{% trans "Delete selected objects" %}</button>
                        <button type="submit" class="btn btn-outline-primary px-2 mt-2 ms-2" name="delete" value="all">{% trans "Delete all objects" %}</button>
                        <button type="submit" class="btn btn-outline-primary px-2 mt-2 ms-2" name="setOrdering" value="set">{% trans "Save reordering" %}</button>
                    </div>
                </form>
            {% endif %}

            <div class="d-flex justify-content-center">
                <a class="btn btn-outline-primary px-2 mt-2" href="{% url "candles:settingCreate" %}">{% trans "Add new security tracking" %}</a>
                <form method="post" action="{% url "candles:addTopByCapStocks" %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-primary px-2 mt-2 ms-2">{% trans "Add top 150 stocks by capitalization" %}</button>
                </form>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>
{% endblock %}

{% block include_js %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $( function() {
        $( "#sortable" ).sortable();
    });

    $("#checkAll").click(function(){
        $('.deleteObject input:checkbox').not(this).prop('checked', this.checked);
    });
</script>
{% endblock %}

app/templates/securitySettings/update.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Edit security" %}{% endblock %}

{% block content %}
<div class="row my-4">
  <div class="col-2"></div>
  <div class="col-8">
    <h3>{% trans "Edit tracking of security" %}</h3>
    <form method="post" enctype="multipart/form-data">
      {% crispy security_form %}
      {% crispy fetchSetting_form %}
      {% crispy userSecuritySettings_form %}
      <button type="submit" class="btn btn-primary px-5 mt-2">{% trans "Save changes" %}</button>
    </form>
  </div>
</div>
{% endblock %}