app/account/urls.py
import django.urls as dj_urls
from . import views

app_name = "account"

urlpatterns = [
    dj_urls.path('', views.dashboard, name='dashboard'),
    dj_urls.path('login/', views.EmailLoginView.as_view(), name='login'),
    dj_urls.path('register/', views.register, name='register'),
    dj_urls.path('edit/', views.edit, name='edit'),
    dj_urls.path('password_change/', views.PasswordChangeView.as_view(
        success_url=dj_urls.reverse_lazy('account:password_change_done')), name='password_change'),
    dj_urls.path('password_reset/', views.PasswordResetView.as_view(
        success_url=dj_urls.reverse_lazy('account:password_reset_done')),
        name='password_reset'),
    dj_urls.path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
        success_url=dj_urls.reverse_lazy('account:password_reset_complete')),
        name='password_reset_confirm'),  # mb TODO
    dj_urls.path('', dj_urls.include('django.contrib.auth.urls')),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from . import views

urlpatterns = i18n_patterns(
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('candles/', include('candles.urls', namespace='candles')),
)

urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n"))
]

app/candles/urls.py
""" Urls for tabs 'Settings of securities', 'Candles', 'Returns'."""
import django.urls as dj_urls
from . import views


app_name = 'candles'

urlpatterns = [
    dj_urls.path('', views.getCandlesPreview, name='list'),
    dj_urls.path('candlesData/', views.getCandles, name='candlesData'),
    dj_urls.path('returnsTask/', views.returnsTask, name='returnsTask'),
    dj_urls.path('trackingSettings/', views.SecuritySettingListView.as_view(), name='settingList'),
    dj_urls.path('trackingSettings/add/',
                 views.createSecuritySetting, name='settingCreate'),
    dj_urls.path('trackingSettings/addTopByCapStocks/',
                 views.addStocksTopByCap, name='addTopByCapStocks'),
    dj_urls.path('trackingSettings/chooseAction/', views.chooseAction, name='chooseAction'),
    dj_urls.path('trackingSettings/bulkDeleteConfirm/',
                 views.bulkDeleteConfirm, name='settingBulkDeleteConfirm'),
    dj_urls.path('trackingSettings/<pk>/edit/', views.updateSecuritySetting, name='settingUpdate'),
]

app/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    </head>
  <body>
    
    <nav class="navbar navbar-expand sticky-top pt-1 pb-0 px-1" style="background-color: var(--bs-body-bg);">
      <div class="container-fluid px-0">
      <ul class="nav nav-tabs rounded-4 bg-black">
        <li class="nav-item">
          <a {% if section == "home" %} class="nav-link border active" {% else %} class="nav-link" {% endif %}
              href="{% url "home" %}">{% trans "Home" %}</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a {% if section == "dashboard" %} class="nav-link border active" {% else %} class="nav-link" {% endif %}
              href="{% url "account:dashboard" %}">{% trans "Account" %}</a>
        </li>
        <li class="nav-item">
          <a {% if section == "SecuritySettings" %} class="nav-link border active"{% else %} class="nav-link" {% endif %}
              href="{% url "candles:settingList" %}">{% trans "Settings of securities" %}</a>
        </li>
        <li class="nav-item">
          <a {% if section == "candles" %} class="nav-link border active"{% else %} class="nav-link" {% endif %}
              href="{% url "candles:list" %}">{% trans "Candles" %}</a>
        </li>
        <li class="nav-item">
          <a {% if section == "returns" %} class="nav-link border active"{% else %} class="nav-link" {% endif %}
              href="{% url "candles:returnsTask" %}">{% trans "Returns" %}</a>
        </li>
        {% endif %}
      </ul>
      
      <span class="navbar-text px-3">
        {% if request.user.is_authenticated %}
        {% blocktrans with user=request.user.first_name|default:request.user.username%}Hello {{ user }},{% endblocktrans %}
        <a href="{% url "account:logout" %}">{% trans "Logout" %}</a>
        {% else %}
        <a href="{% url "account:login" %}?next={{request.get_full_path}}">{% trans "Log-in" %}</a>
        {% endif %}
      </span>
      </div>
    </nav>

    {% if messages %}
      {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible shadow fade show mt-1" role="alert">
          <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message | safe }}
        </div>
      {% endfor %}

    {% endif %}
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
    <br>
    <hr class="my-1"><p class="text-center my-1">© 2023 Copyright</p>
    {% block include_js %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script>
      document.addEventListener('DOMContentLoaded', (event) => {
          // console.log('DOM fully loaded and parsed');
          {% block domready %}          
          {% endblock %}
        });
    </script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
<div class="container m-2"></div>
    <h4 class='text-center'>{% trans "MOEX Trends Catcher" %}</h4>
    <div class="row mt-3">      
        <div class="col-2"></div>
        <div class="col-8">
        {% blocktrans %}
            <p>This app uses <a href="https://iss.moex.com/iss/reference/155">
                /iss/engines/[engine]/markets/[market]/securities/[security]/candles</a>
            endpoint of MOEX Informational Statistical Server to get OHLCV (open, high, low, close, volume) data 
            for different securities. You need to know <em>engine</em>, <em>market</em> and <em>security</em> params 
            to use this app.
            <br><br>
            All possible <em>engine</em> and <em>market</em> MOEX ISS names -  
            <a href="https://iss.moex.com/iss/index">/iss/index</a>.
            <br><br>
            You can find <em>engine</em> and <em>market</em> parameters for your <em>security</em> using this request:<br>
            <a href="https://iss.moex.com/iss/securities?q=">/iss/securities?q=</a>[security]<br>
            E.g., the value of the column 'group' is 'stock_shares' for q=GAZP. Use stock as engine shares as market.
            Other parameters of this end point - <a href="https://iss.moex.com/iss/reference/5">/iss/reference/5</a>.
            </p>
            <p>
            <strong>After registration</strong> you can <em>add / update / delete / reorder settings</em> to fetch 
            your favourite securities, look at its <em>candle charts</em> with tunable sizes and get info about 
            best possible historical <em>long and short deals</em>. There's one limitation in this version of the app - 
            you can fetch a maximum of only 500 last time intervals for a single security. But it's enough to catch current trend.
            </p><p>
            You can find more information about MOEX Informational Statistical Server and its RESTful API using this 
            <a href="https://www.moex.com/a2193">link</a>.
            </p>
        {% endblocktrans %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/pagination.html
{% load i18n %}
{% load my_tags %}

<nav aria-label="page navigation" class="my-3">
    {% if object_list %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a href="?{% query_transform page=1 %}" class="page-link">1</a></li>
        {% endif %}
        {% if page_obj.previous_page_number != 1 %}
            {% if page_obj.previous_page_number > 2 %}
                <p class="mx-2">...</p>
            {% endif %}
            <li class="page-item">
                <a href="?{% query_transform page=page_obj.previous_page_number %}" class="page-link">{{ page_obj.previous_page_number }}</a>
            </li>
        {% endif %}
        <li class="page-item active">
            <a href="" class="page-link">{{ page_obj.number }}</a>
        </li>
        {% if page_obj.has_next %}        
        <li class="page-item">
            <a href="?{% query_transform page=page_obj.next_page_number %}" class="page-link">{{ page_obj.next_page_number }}</a>
        </li>
        {% endif %}
        {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
            {% if page_obj.paginator.num_pages|add:'-1' > page_obj.next_page_number %}
                <p class="mx-2">...</p>
            {% endif %}
            <li class="page-item">
                <a href="?{% query_transform page=page_obj.paginator.num_pages %}" class="page-link">{{ page_obj.paginator.num_pages }}</a>
            </li>
        {% endif %}
    </ul>
    {% else %}
    <p class="text-center my-2">{% trans "Such objects have not yet been created." %}</p>
    {% endif %}
  </nav>